const tags = [
  "Home décor",
  "Hairstyle",
  "Fashion",
  "Art",
  "Health and fitness",
  "Nails",
  "Draw",
  "Skin care",
  "Make-up",
  "Quotes",
  "Food drink",
  "DIY home décor",
  "Wallpapers",
  "Outfits",
  "Photography",
  "Eye make-up",
  "Plaits",
  "Disney",
  "Flowers",
  "Design",
  "Casual outfits",
  "Tattoos",
  "Desserts",
  "Travel",
  "Cute animals",
  "Shoes",
  "Life quotes",
  "Nature",
  "DIY",
  "Tumblr rooms",
  "Gowns",
  "Cooking",
  "Long prom dresses",
  "Butt workouts",
  "Music",
  "Knitting and crocheting",
  "Harry potter",
  "Anime",
  "Arts and crafts",
  "Furniture",
  "Cute puppies",
  "Inspirational",
  "Kitchen designs",
  "Adorable kittens",
  "Sewing",
  "Relationship goals",
  "Books",
  "Wisdom quotes",
  "Healthy snacks",
  "Wedding",
  "DIY gifts",
  "Nutrition",
  "Manga",
  "Wedding dresses",
  "Celebrities",
  "Relationships",
  "Animation",
  "Milky way",
  "Funny text messages",
  "Memes",
  "Parents",
  "Babies",
  "African fashion",
  "Modern interior design",
  "Trainers",
  "Education",
  "Gardening",
  "Street styles",
  "Humour",
  "Easy crafts",
  "Baking",
  "Anime girls",
  "Healthy recipes",
  "Writing",
  "Brows",
  "Diet meal plans",
  "Interesting facts",
  "House architecture",
  "Love quotes",
  "Piercing",
  "Birthdays",
  "Animals",
  "K-pop",
  "Fitness",
  "Beauty",
  "Hair tutorials",
  "Coffin nails",
  "Wallpaper quotes",
  "Technology",
  "Movies",
  "Health",
  "Food",
  "Science",
  "Visiting and Travel",
  "Business",
  "Psychology",
  "History",
  "Sports",
  "Fashion and Style",
  "Economics",
  "Mathematics",
  "Philosophy",
  "Politics",
  "Finance",
  "Marketing",
  "Television Series",
  "Fine Art",
  "Literature",
  "Journalism"
]
